//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Coop.CreditUnionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreditUnionServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CreditUnionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCreditUnionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCreditUnionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditUnionsByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCreditUnionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCreditUnionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreditUnionService() {
            this.Url = global::Coop.Properties.Settings.Default.Coop_CreditUnionService_CreditUnionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCreditUnionCompletedEventHandler GetCreditUnionCompleted;
        
        /// <remarks/>
        public event GetAllCreditUnionsCompletedEventHandler GetAllCreditUnionsCompleted;
        
        /// <remarks/>
        public event GetCreditUnionsByNameCompletedEventHandler GetCreditUnionsByNameCompleted;
        
        /// <remarks/>
        public event UpdateCreditUnionCompletedEventHandler UpdateCreditUnionCompleted;
        
        /// <remarks/>
        public event CreateCreditUnionCompletedEventHandler CreateCreditUnionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCreditUnion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditUnion GetCreditUnion(int id) {
            object[] results = this.Invoke("GetCreditUnion", new object[] {
                        id});
            return ((CreditUnion)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditUnionAsync(int id) {
            this.GetCreditUnionAsync(id, null);
        }
        
        /// <remarks/>
        public void GetCreditUnionAsync(int id, object userState) {
            if ((this.GetCreditUnionOperationCompleted == null)) {
                this.GetCreditUnionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditUnionOperationCompleted);
            }
            this.InvokeAsync("GetCreditUnion", new object[] {
                        id}, this.GetCreditUnionOperationCompleted, userState);
        }
        
        private void OnGetCreditUnionOperationCompleted(object arg) {
            if ((this.GetCreditUnionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditUnionCompleted(this, new GetCreditUnionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCreditUnions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditUnion[] GetAllCreditUnions() {
            object[] results = this.Invoke("GetAllCreditUnions", new object[0]);
            return ((CreditUnion[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCreditUnionsAsync() {
            this.GetAllCreditUnionsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCreditUnionsAsync(object userState) {
            if ((this.GetAllCreditUnionsOperationCompleted == null)) {
                this.GetAllCreditUnionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCreditUnionsOperationCompleted);
            }
            this.InvokeAsync("GetAllCreditUnions", new object[0], this.GetAllCreditUnionsOperationCompleted, userState);
        }
        
        private void OnGetAllCreditUnionsOperationCompleted(object arg) {
            if ((this.GetAllCreditUnionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCreditUnionsCompleted(this, new GetAllCreditUnionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCreditUnionsByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditUnion[] GetCreditUnionsByName(string filter) {
            object[] results = this.Invoke("GetCreditUnionsByName", new object[] {
                        filter});
            return ((CreditUnion[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditUnionsByNameAsync(string filter) {
            this.GetCreditUnionsByNameAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetCreditUnionsByNameAsync(string filter, object userState) {
            if ((this.GetCreditUnionsByNameOperationCompleted == null)) {
                this.GetCreditUnionsByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditUnionsByNameOperationCompleted);
            }
            this.InvokeAsync("GetCreditUnionsByName", new object[] {
                        filter}, this.GetCreditUnionsByNameOperationCompleted, userState);
        }
        
        private void OnGetCreditUnionsByNameOperationCompleted(object arg) {
            if ((this.GetCreditUnionsByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditUnionsByNameCompleted(this, new GetCreditUnionsByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCreditUnion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditUnion UpdateCreditUnion(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong) {
            object[] results = this.Invoke("UpdateCreditUnion", new object[] {
                        userHash,
                        id,
                        newName,
                        newAbbr,
                        newWWW,
                        newLat,
                        newLong});
            return ((CreditUnion)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCreditUnionAsync(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong) {
            this.UpdateCreditUnionAsync(userHash, id, newName, newAbbr, newWWW, newLat, newLong, null);
        }
        
        /// <remarks/>
        public void UpdateCreditUnionAsync(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong, object userState) {
            if ((this.UpdateCreditUnionOperationCompleted == null)) {
                this.UpdateCreditUnionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCreditUnionOperationCompleted);
            }
            this.InvokeAsync("UpdateCreditUnion", new object[] {
                        userHash,
                        id,
                        newName,
                        newAbbr,
                        newWWW,
                        newLat,
                        newLong}, this.UpdateCreditUnionOperationCompleted, userState);
        }
        
        private void OnUpdateCreditUnionOperationCompleted(object arg) {
            if ((this.UpdateCreditUnionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCreditUnionCompleted(this, new UpdateCreditUnionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateCreditUnion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditUnion CreateCreditUnion(string userHash, string name, string abbr, string www, double latitude, double longitude) {
            object[] results = this.Invoke("CreateCreditUnion", new object[] {
                        userHash,
                        name,
                        abbr,
                        www,
                        latitude,
                        longitude});
            return ((CreditUnion)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCreditUnionAsync(string userHash, string name, string abbr, string www, double latitude, double longitude) {
            this.CreateCreditUnionAsync(userHash, name, abbr, www, latitude, longitude, null);
        }
        
        /// <remarks/>
        public void CreateCreditUnionAsync(string userHash, string name, string abbr, string www, double latitude, double longitude, object userState) {
            if ((this.CreateCreditUnionOperationCompleted == null)) {
                this.CreateCreditUnionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCreditUnionOperationCompleted);
            }
            this.InvokeAsync("CreateCreditUnion", new object[] {
                        userHash,
                        name,
                        abbr,
                        www,
                        latitude,
                        longitude}, this.CreateCreditUnionOperationCompleted, userState);
        }
        
        private void OnCreateCreditUnionOperationCompleted(object arg) {
            if ((this.CreateCreditUnionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCreditUnionCompleted(this, new CreateCreditUnionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditUnion {
        
        private int idField;
        
        private string nameField;
        
        private string abbrField;
        
        private string websiteField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Abbr {
            get {
                return this.abbrField;
            }
            set {
                this.abbrField = value;
            }
        }
        
        /// <remarks/>
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCreditUnionCompletedEventHandler(object sender, GetCreditUnionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditUnionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditUnionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditUnion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditUnion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllCreditUnionsCompletedEventHandler(object sender, GetAllCreditUnionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCreditUnionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCreditUnionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditUnion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditUnion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCreditUnionsByNameCompletedEventHandler(object sender, GetCreditUnionsByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditUnionsByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditUnionsByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditUnion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditUnion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateCreditUnionCompletedEventHandler(object sender, UpdateCreditUnionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCreditUnionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCreditUnionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditUnion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditUnion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateCreditUnionCompletedEventHandler(object sender, CreateCreditUnionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCreditUnionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCreditUnionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreditUnion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreditUnion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591