//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFWeb2.CreditUnionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditUnionService.CreditUnionServiceSoap")]
    public interface CreditUnionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCreditUnion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.CreditUnionService.CreditUnion GetCreditUnion(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCreditUnion", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> GetCreditUnionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCreditUnions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.CreditUnionService.CreditUnion[] GetAllCreditUnions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCreditUnions", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion[]> GetAllCreditUnionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCreditUnionsByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.CreditUnionService.CreditUnion[] GetCreditUnionsByName(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCreditUnionsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion[]> GetCreditUnionsByNameAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCreditUnion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.CreditUnionService.CreditUnion UpdateCreditUnion(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCreditUnion", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> UpdateCreditUnionAsync(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCreditUnion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.CreditUnionService.CreditUnion CreateCreditUnion(string userHash, string name, string abbr, string www, double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCreditUnion", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> CreateCreditUnionAsync(string userHash, string name, string abbr, string www, double latitude, double longitude);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditUnion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string abbrField;
        
        private string websiteField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Abbr {
            get {
                return this.abbrField;
            }
            set {
                this.abbrField = value;
                this.RaisePropertyChanged("Abbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditUnionServiceSoapChannel : SCFWeb2.CreditUnionService.CreditUnionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditUnionServiceSoapClient : System.ServiceModel.ClientBase<SCFWeb2.CreditUnionService.CreditUnionServiceSoap>, SCFWeb2.CreditUnionService.CreditUnionServiceSoap {
        
        public CreditUnionServiceSoapClient() {
        }
        
        public CreditUnionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditUnionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditUnionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditUnionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SCFWeb2.CreditUnionService.CreditUnion GetCreditUnion(int id) {
            return base.Channel.GetCreditUnion(id);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> GetCreditUnionAsync(int id) {
            return base.Channel.GetCreditUnionAsync(id);
        }
        
        public SCFWeb2.CreditUnionService.CreditUnion[] GetAllCreditUnions() {
            return base.Channel.GetAllCreditUnions();
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion[]> GetAllCreditUnionsAsync() {
            return base.Channel.GetAllCreditUnionsAsync();
        }
        
        public SCFWeb2.CreditUnionService.CreditUnion[] GetCreditUnionsByName(string filter) {
            return base.Channel.GetCreditUnionsByName(filter);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion[]> GetCreditUnionsByNameAsync(string filter) {
            return base.Channel.GetCreditUnionsByNameAsync(filter);
        }
        
        public SCFWeb2.CreditUnionService.CreditUnion UpdateCreditUnion(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong) {
            return base.Channel.UpdateCreditUnion(userHash, id, newName, newAbbr, newWWW, newLat, newLong);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> UpdateCreditUnionAsync(string userHash, int id, string newName, string newAbbr, string newWWW, double newLat, double newLong) {
            return base.Channel.UpdateCreditUnionAsync(userHash, id, newName, newAbbr, newWWW, newLat, newLong);
        }
        
        public SCFWeb2.CreditUnionService.CreditUnion CreateCreditUnion(string userHash, string name, string abbr, string www, double latitude, double longitude) {
            return base.Channel.CreateCreditUnion(userHash, name, abbr, www, latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.CreditUnionService.CreditUnion> CreateCreditUnionAsync(string userHash, string name, string abbr, string www, double latitude, double longitude) {
            return base.Channel.CreateCreditUnionAsync(userHash, name, abbr, www, latitude, longitude);
        }
    }
}
