//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCFWeb2.DonationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DonationService.DonationServiceSoap")]
    public interface DonationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDonation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation AddDonation(
                    string userHash, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDonation", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> AddDonationAsync(
                    string userHash, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDonation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteDonation(string userHash, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDonation", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteDonationAsync(string userHash, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDonation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation UpdateDonation(
                    string userHash, 
                    int id, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDonation", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> UpdateDonationAsync(
                    string userHash, 
                    int id, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation GetDonation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonation", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> GetDonationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByCreditUnion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation[] GetDonationsByCreditUnion(int creditUnion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByCreditUnion", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByCreditUnionAsync(int creditUnion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation[] GetDonationsByCategory(int category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByCategoryAsync(int category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCFWeb2.DonationService.Donation[] GetDonationsByDate(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDonationsByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByDateAsync(System.DateTime start, System.DateTime end);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Donation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private CreditUnion donatingCreditUnionField;
        
        private string titleField;
        
        private int categoryField;
        
        private int onClockHoursField;
        
        private int offClockHoursField;
        
        private int totalHoursField;
        
        private int dollarsField;
        
        private int otherContributionsValueField;
        
        private int totalDollarValueField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zIPField;
        
        private string countryField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string additionalInfoField;
        
        private System.DateTime donationDateField;
        
        private System.DateTime dateAddedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CreditUnion DonatingCreditUnion {
            get {
                return this.donatingCreditUnionField;
            }
            set {
                this.donatingCreditUnionField = value;
                this.RaisePropertyChanged("DonatingCreditUnion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OnClockHours {
            get {
                return this.onClockHoursField;
            }
            set {
                this.onClockHoursField = value;
                this.RaisePropertyChanged("OnClockHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int OffClockHours {
            get {
                return this.offClockHoursField;
            }
            set {
                this.offClockHoursField = value;
                this.RaisePropertyChanged("OffClockHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TotalHours {
            get {
                return this.totalHoursField;
            }
            set {
                this.totalHoursField = value;
                this.RaisePropertyChanged("TotalHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Dollars {
            get {
                return this.dollarsField;
            }
            set {
                this.dollarsField = value;
                this.RaisePropertyChanged("Dollars");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OtherContributionsValue {
            get {
                return this.otherContributionsValueField;
            }
            set {
                this.otherContributionsValueField = value;
                this.RaisePropertyChanged("OtherContributionsValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int TotalDollarValue {
            get {
                return this.totalDollarValueField;
            }
            set {
                this.totalDollarValueField = value;
                this.RaisePropertyChanged("TotalDollarValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
                this.RaisePropertyChanged("ZIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AdditionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("AdditionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime DonationDate {
            get {
                return this.donationDateField;
            }
            set {
                this.donationDateField = value;
                this.RaisePropertyChanged("DonationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
                this.RaisePropertyChanged("DateAdded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditUnion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string abbrField;
        
        private string websiteField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Abbr {
            get {
                return this.abbrField;
            }
            set {
                this.abbrField = value;
                this.RaisePropertyChanged("Abbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DonationServiceSoapChannel : SCFWeb2.DonationService.DonationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DonationServiceSoapClient : System.ServiceModel.ClientBase<SCFWeb2.DonationService.DonationServiceSoap>, SCFWeb2.DonationService.DonationServiceSoap {
        
        public DonationServiceSoapClient() {
        }
        
        public DonationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DonationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SCFWeb2.DonationService.Donation AddDonation(
                    string userHash, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID) {
            return base.Channel.AddDonation(userHash, creditUnion, title, category, onclock, offclock, dollars, otherContributions, address1, address2, city, state, zip, country, latitude, longitude, additionalInfo, donationDate, userID);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> AddDonationAsync(
                    string userHash, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID) {
            return base.Channel.AddDonationAsync(userHash, creditUnion, title, category, onclock, offclock, dollars, otherContributions, address1, address2, city, state, zip, country, latitude, longitude, additionalInfo, donationDate, userID);
        }
        
        public void DeleteDonation(string userHash, int id) {
            base.Channel.DeleteDonation(userHash, id);
        }
        
        public System.Threading.Tasks.Task DeleteDonationAsync(string userHash, int id) {
            return base.Channel.DeleteDonationAsync(userHash, id);
        }
        
        public SCFWeb2.DonationService.Donation UpdateDonation(
                    string userHash, 
                    int id, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID) {
            return base.Channel.UpdateDonation(userHash, id, creditUnion, title, category, onclock, offclock, dollars, otherContributions, address1, address2, city, state, zip, country, latitude, longitude, additionalInfo, donationDate, userID);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> UpdateDonationAsync(
                    string userHash, 
                    int id, 
                    int creditUnion, 
                    string title, 
                    int category, 
                    int onclock, 
                    int offclock, 
                    int dollars, 
                    int otherContributions, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zip, 
                    string country, 
                    double latitude, 
                    double longitude, 
                    string additionalInfo, 
                    System.DateTime donationDate, 
                    int userID) {
            return base.Channel.UpdateDonationAsync(userHash, id, creditUnion, title, category, onclock, offclock, dollars, otherContributions, address1, address2, city, state, zip, country, latitude, longitude, additionalInfo, donationDate, userID);
        }
        
        public SCFWeb2.DonationService.Donation GetDonation(int id) {
            return base.Channel.GetDonation(id);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation> GetDonationAsync(int id) {
            return base.Channel.GetDonationAsync(id);
        }
        
        public SCFWeb2.DonationService.Donation[] GetDonationsByCreditUnion(int creditUnion) {
            return base.Channel.GetDonationsByCreditUnion(creditUnion);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByCreditUnionAsync(int creditUnion) {
            return base.Channel.GetDonationsByCreditUnionAsync(creditUnion);
        }
        
        public SCFWeb2.DonationService.Donation[] GetDonationsByCategory(int category) {
            return base.Channel.GetDonationsByCategory(category);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByCategoryAsync(int category) {
            return base.Channel.GetDonationsByCategoryAsync(category);
        }
        
        public SCFWeb2.DonationService.Donation[] GetDonationsByDate(System.DateTime start, System.DateTime end) {
            return base.Channel.GetDonationsByDate(start, end);
        }
        
        public System.Threading.Tasks.Task<SCFWeb2.DonationService.Donation[]> GetDonationsByDateAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetDonationsByDateAsync(start, end);
        }
    }
}
